matrix:
  include:
  - os: linux
    sudo: false
    language: android
    android:
      components:
      - tools
      - platform-tools
      - build-tools-26.0.2
      - android-27
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository
    addons:
      apt:
        sources:
        - sourceline: deb https://dl.yarnpkg.com/debian/ stable main
          key_url: https://dl.yarnpkg.com/debian/pubkey.gpg
        packages:
        - oracle-java8-installer
        - oracle-java8-set-default
        - npm
    licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/Library/Caches/npm/"
  - "$HOME/.cache/npm/"
before_install:
- yes | sdkmanager "platforms;android-26"
- nvm install 8
- npm i -g ionic cordova
script:
- npm i
- ionic cordova build android --minifyjs --minifycss --optimizejs --prod --release
env:
  global:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: kPG5TmVdc6isVaE+gZK++CivoW5oWb0sV5JW3425JXM7o/rr7BrrM/Le4cObkuLu1EJyqYwBBScyUi+/uM7HmV40GGl2eurUU4Gtf5nk6mxv93B+ncS5RbNGSa6bYno8gPC9VoyqZDpjgjCEgrh91m1vLQ4FMC9Q4wlbKOd8hoUVovtMTqoEAR+cNtr8jeGinYOjuUAVsY/6nqNoNDA+CEexrzXM9wPALy4GCo+2noBXlZJns7PG1kOU5SDRRn5lgo4zM8MeK9vfqUqbuemvDNATgs97xdlxo6VvCSigjRgx0GbnBTPET7gs2S+3z5TUqDgwCT6acB0fF2vASc63tTMZlqoKjI+iW8IDvt+GqusM7YTf7pctqASMSxNg6qahqj/opvYsjY8qcD9NdlYLz2t5BHr83mgJgfRKVmoe5qMrhft1kd2FyxzjnTfcRjAj9eQZYrdlnySS6Uc8X7L37BZ/0qjLnxaw+bITY+pyWjzbxjiGzfeAVDH62v9SXGRp6mVhtUZOVHkhaGC0XVpLNxqyK0YcD68Gevu6myUHLG12Sw0hxQ72RHdKqTqa/UnFgl7P41bigvwzuwnSE3DPbVNJtIDhHoqWPeauitdy3R6HSjnh0GGV9mdAjg8pSgdXlkau7Bq+Zd3nfolup9bZW44R1FdX7J7aVtYQAo3LfzE=
  file: "/home/travis/build/AndreVarandas/space-x-explorer/platforms/android/build/outputs/apk/release/*"
  on:
    repo: AndreVarandas/space-x-explorer
    tags: true
    all_branches: true
