branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+$/"

matrix:
  include:
  - os: linux
    sudo: false
    language: android
    android:
      components:
      - tools
      - platform-tools
      - build-tools-26.0.2
      - android-27
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository

    addons:
      apt:
        sources:
        - sourceline: deb https://dl.yarnpkg.com/debian/ stable main
          key_url: https://dl.yarnpkg.com/debian/pubkey.gpg
        packages:
        - oracle-java8-installer
        - oracle-java8-set-default
        - npm

    licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/Library/Caches/npm/"
  - "$HOME/.cache/npm/"

before_install:
- yes | sdkmanager "platforms;android-26"
- nvm install 8
- npm i -g ionic cordova

script:
- npm i
- ionic cordova build android --minifyjs --minifycss --optimizejs --prod --release

env:
  global:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: CyjUZQJRBYcPTjOrEuTn983HMT85HGzB7GbTkkUyEqtc51FgfyxL/L9EXeK22/xAgWpE81r0l1GLxUcNC3ERvvvAsSJ7ksyCIn1AhKyVxyHsvBtbFMshLrbHc6925O74awIFVKfuJBB44kFB73FhgZfLqicv4J0xEb2elF2zA6VEk3iUrk5peHFTfpEstEjQWnSKZlCcO5qrRAScBXgZcwyVFp/QguhIruJKEWogPnVM8Uv9Z8L6l2aaiYgZBrUgzyY1vJJqBsCbmQgrGAb0PE+kRx7rj/OGV/L+B8vVaF2VRAUsFrbXbk+8+h+KvO/wpIGQ6nChNT6k6Scw839YHiEoCHwR5b4R/PJjtGLHmqGcQPz3zaDADnDaN88XLt62fYUf8Z/Lpbkk3sgscd4QDX0Cdyob6C9scU/iXKeB8sq/ZinG+kEsaDnk0Z27kS6ETCBDw5V8BjtBU7DvV80iN3E0gg5J0UUluK6PuFWqi4tUL205TxtZLX9WnpR1B4Q2NkIalw2LSFgL06Pt2/Fv+d45rPH38yoHCFia7x3o1hqi2r+FuhAvJxhP384cWPoUTH61SThTvlvFY+DRz6BV0sbi/sNJr8MlXHwlMirjrP5tjokStfpAlCpx+0xP7Ys0tcxWjCo3sPalZCpJHyUWd3qJC1gCzqZeJaE+W0mKVkU=
  file: "/home/travis/build/AndreVarandas/space-x-explorer/platforms/android/build/outputs/apk/release/*"
  on:
    repo: AndreVarandas/space-x-explorer
    tags: true
