language: android

sudo: false

env:
  global:
    - ANDROID_API=27
    - ANDROID_BUILD_TOOLS=26.0.2

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-$ANDROID_API"
  - yes | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS"
  # - curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
  # - sudo apt-get install nodejs
  # - sudo apt-get install build-essential
  - nvm install 8
  - npm i -g ionic cordova

jdk:
  - oraclejdk8

script:
  - npm i
  - ionic cordova build android --minifyjs --minifycss --optimizejs --prod --release

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.android/build-cache"
    - "$HOME/.m2"
    - "$HOME/.gradle"
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
    - "$HOME/Library/Caches/npm/"
    - "$HOME/.cache/npm/"

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: ay5O9+SdiBtDhuSS1J9k5lzz0dJvsC+mPRYHyBX1N75IvnHy4xk1O7VeFyfFc+Z5RP6UFeXNI+jIICfzEUBWuufYhu/prqUNOZOCCDY34dbMXeXLARjoYUoOb6Xpn8V6SlvmLqC54dwNGbzQ6rNvJPEvsK1TIPbFNeycX4gK87jTNEYX4VPFRLQNI6DMWSamEb5YsfznwrSOR/N6WhAig6iplUPXym90GL6clOKFAutgTAUcTgMq59Wpr3uqxgQSPhzAEqISC3wQPUSh1t7qmPfKKhWupUU5ddyamzK8NCZSckKTv1f10CoMJn+nFEnKwIAt72E7aMy1iwcMWdgNge/wc5sJVOqODmrlY7xMfdj0PCwEZNoxpgztbrD3QyVfYFmPzp94feXJU0UqdXhJ5qZDhJGrYvfw5gzSz5/YGMGY5LQ1oM1hOtvanTOR/P4u7IHj97uOf+Pqc1fvc7WEIwFSrfAuVE5UzDacBq+vsnO6v4SaD2CR14BdFgvXIWSFMqP2k8TSZLZggg+b1tWHbk9xrI/XnsF6DZUxRHkd6B8YMca8pNueeQGF0Vo2hMXysOlLx/pNb213C93tQcVYHtxZ5o5HxiueU999jKZEecewQbXRYkXC8C9+V2U59D0HwhxibDpoqQeCQycUYRRkymakZz5lO/d6V2YPYkRrfQg=
  file: "/home/travis/build/AndreVarandas/space-x-explorer/platforms/android/app/build/outputs/apk/release/*"
  on:
    repo: AndreVarandas/space-x-explorer
    tags: true
    all_branches: true